name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-2022

    steps:     
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: Swatinem/rust-cache@v1.3.0
    - name: Generate Repo
      run: |
        cd ..
        cargo generate -p rust_quickstart -n test -d ask_for_logging=true -d ask_for_errors=true -d description="For github" -s    - name: Build
    - name: Build Test
      run: |
        cd test
        cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
